# Site settings
title: Luís Duarte
header-img: img/lisbon.jpg
email: lduarte@luisduarte.net
copyright_name: Luís Duarte
description: "Personal Website"
baseurl: ""
url: "http://luisduarte.net"
twitter_username: driverpt
github_username:  driverpt
#facebook_username:  driver.pt
email_username:  lduarte AT luisduarte DOT net

future: true

disqus:
  shortname: chroniclesofasoftwareengineer

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: "UA-37165501-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
