# Site settings
title: Luís Duarte
header-img: img/lisbon.jpg
email: lduarte@luisduarte.net
copyright_name: Luís Duarte
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://driverpt.github.io"
twitter_username: driverpt
github_username:  driverpt
#facebook_username:  driver.pt
email_username:  lduarte AT luisduarte DOT net

disqus:
  shortname: chroniclesofasoftwareengineer

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-paginate
  - jekyll-feed
